name: paddle
channels:
  # You can use the TUNA mirror to speed up the installation if you are in mainland China.
  # - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pytorch=1.7.0
  - torchvision=0.8.1
  - cudatoolkit=10.2
  - tqdm
  - thop
  - numpy
  - opencv
  - loguru
  - scikit-image
  - Pillow
  - ninja
  - tabulate
  - tensorboard
